# Projektoplæg
Projektet er tænkt som træning til eksamensforløbet, derfor skal i skrive en rapport af samme type, dog i mindre udgave, i dette
tilfælde er rapportstørrelsen: 10 – 20 sider + 2 – 7 sider pr. ekstra gruppe medlem. Skabelonen til rapporten kan findes i Dokumenter og i intro timen på lectio torsdag den 2/10. Husk i skal beskrive jeres tekniske metoder og anvendelse.

Gruppestørrelse: 2 – 4 personer ( solo og 5 personers grupper skal have dispensation ).

Projektperioden går fra den 2/10 til og med den 11/12, alle teknikfagstimer bruges.

Projektet skal afleveres som video trailer ( ligesom når rigtige spil laver teaser eller launch trailer ).

Projektet skal dertil afleveres som build og package på et drive link

Projektet skal omhandle aspekter af cyber security, der er dog ikke stramme begrænsninger på formatet, så hvis i vil lave en DDoS simulator i form af en udgave af ”Breakout” er det fuldt tilladt.


# Problemanalyse

# Software og Materialelister

# Projektafgrænsning

## Must Have, Should Have, Could Have, Wont Have (MoSCoW)

# Planlægning

## Gantt diagram
## SCRUM

# Metoder og redskaber


## Analysemodeller til målgruppeundersøgelse

### MDA (Mechanics, Dynamics, Aesthetics)
### Bartle's spillertyper
### Flow teori

## Målgruppeanalyse
### Minerva
### RISC og Conzoom

## Metoder til design af UI
## Designprincipper
## CRAP modellen
## Farveteori og kontraster
## Formteori

# Idégenerering

# Valg af idé kandidater / koncept / design

## Flowchart over logik

# Konkurrence research
Amongs Us
Dale & Dawson
Job Simulator

## Videnskabelig hjemmel eller belæg

# Skitser af kandidater

## Moodboards og referencer

# Udvælgelse af kandidater

# Paper dummy
f

## Første usability test
## Ændring af paper dummy som følge af feedback
## Evt. usability test igen

# Kravspecifikation til Digital dummy


# Digital dummy


## Usability test

# Digital dummy / Usability


# Endelige produkt


# Produktbeskrivelse

