project:
    render:
        - synopsis.qmd
    preview:
        browser: false

lang: da
bibliography: 7_referencer.bib 
csl: ieee-with-url.csl
filters:
   - include-code-files

format:
    pdf:
        papersize: "a4"
        geometry:
            - top=2.5cm
            - bottom=2.5cm
            - left=2cm
            - right=2cm
        documentclass: "article"
        number-sections: true
        code-line-numbers: true
        include-in-header:
            text: |
                \usepackage{icomma}
                \usepackage{lastpage}
                \usepackage{fancyhdr}
                \pagestyle{fancy}
                \fancyhf{} 
                \lhead{ {{< meta navn >}} }
                \chead{ {{< meta titel >}} }
                \rhead{ {{< meta fag >}} }
                \cfoot{Side \thepage\ af \pageref{LastPage}}
                \definecolor{codecolor}{rgb}{.9,.9,.9}
                \let\oldtexttt\texttt
                \renewcommand{\texttt}[1]{\setlength{\fboxsep}{0pt}\colorbox{codecolor}{\vphantom{,!}\oldtexttt{#1}}}
        include-before-body:
            text: |
                \begin{titlepage}
                    \begin{center}
                        {\textbf{\Huge {{< meta titel >}} }} \\[1em]
                        {\Large {{< meta fag >}} } \\[1em]
                        \textbf{ {{< meta navn >}} - {{< meta klasse >}} }

                        \vfill
                        \includegraphics[width=0.75\textwidth,height=0.75\textwidth,keepaspectratio]{img/cover.png}
                        \vfill

                        {\large ZBC Slagelse HTX d. {{< meta dato >}} } \\[1em]
                        \textbf{Vejleder}: {{< meta vejleder >}} \\[1em]
                    \end{center}
                \end{titlepage}

                \hypersetup{linkcolor=black}
